In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)
print("shape:", a.shape)
print("dtype:", a.dtype)


[1 2 3 4 5]
shape: (5,)
dtype: int64


In [2]:
temps = np.array([-4, -3, 2, 9, 15, 19, 21, 20, 14, 8, 2, -2])

days_in_month = np.array([31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31])

month_numbers = np.arange(1, 13)

print("temps:", temps)
print("shape:", temps.shape, "dtype:", temps.dtype)

print("days_in_month:", days_in_month)
print("shape:", days_in_month.shape, "dtype:", days_in_month.dtype)

print("month_numbers:", month_numbers)
print("shape:", month_numbers.shape, "dtype:", month_numbers.dtype)


temps: [-4 -3  2  9 15 19 21 20 14  8  2 -2]
shape: (12,) dtype: int64
days_in_month: [31 28 31 30 31 30 31 31 30 31 30 31]
shape: (12,) dtype: int64
month_numbers: [ 1  2  3  4  5  6  7  8  9 10 11 12]
shape: (12,) dtype: int64


In [3]:
temps_f = temps * 9 / 5 + 32

print("Температура у °F:")
print(temps_f)

warm_days = days_in_month[temps > 15]
total_warm_days = warm_days.sum()

print("Кількість днів із температурою вище 15°C:", total_warm_days)

print("Кількість днів у році:", days_in_month.sum())
print("Чи дорівнює 365:", days_in_month.sum() == 365)


Температура у °F:
[24.8 26.6 35.6 48.2 59.  66.2 69.8 68.  57.2 46.4 35.6 28.4]
Кількість днів із температурою вище 15°C: 92
Кількість днів у році: 365
Чи дорівнює 365: True


In [4]:
warmest_index = temps.argmax()
coldest_index = temps.argmin()

print("Найтепліший місяць:")
print("індекс:", warmest_index)
print("номер місяця:", month_numbers[warmest_index])
print("температура:", temps[warmest_index], "°C")

print("\nНайхолодніший місяць:")
print("індекс:", coldest_index)
print("номер місяця:", month_numbers[coldest_index])
print("температура:", temps[coldest_index], "°C")

below_zero_months = month_numbers[temps < 0]
print("\nМісяці з температурою нижче нуля:", below_zero_months)

sorted_temps = np.sort(temps)
print("\nТемператури за зростанням:", sorted_temps)

print("Оригінальний temps:", temps)


Найтепліший місяць:
індекс: 6
номер місяця: 7
температура: 21 °C

Найхолодніший місяць:
індекс: 0
номер місяця: 1
температура: -4 °C

Місяці з температурою нижче нуля: [ 1  2 12]

Температури за зростанням: [-4 -3 -2  2  2  8  9 14 15 19 20 21]
Оригінальний temps: [-4 -3  2  9 15 19 21 20 14  8  2 -2]


In [5]:
sun_hours = np.array([
    55, 70, 110, 150, 220, 240,
    260, 245, 180, 120, 65, 50
])

data = np.array([temps, days_in_month, sun_hours])

print("data:")
print(data)

print("shape:", data.shape)

print("\nСума кожного рядка:")
print(data.sum(axis=1))

print("\nСереднє кожного рядка:")
print(data.mean(axis=1))

print("\nСума кожного стовпця:")
print(data.sum(axis=0))


data:
[[ -4  -3   2   9  15  19  21  20  14   8   2  -2]
 [ 31  28  31  30  31  30  31  31  30  31  30  31]
 [ 55  70 110 150 220 240 260 245 180 120  65  50]]
shape: (3, 12)

Сума кожного рядка:
[ 101  365 1765]

Середнє кожного рядка:
[  8.41666667  30.41666667 147.08333333]

Сума кожного стовпця:
[ 82  95 143 189 266 289 312 296 224 159  97  79]


In [6]:
rows = np.array([temps, days_in_month])

print("rows:")
print(rows)
print("shape:", rows.shape)

correction = np.array([1, 0])

print("\ncorrection:")
print(correction)
print("shape:", correction.shape)

# Спробуйте:
rows + correction


rows:
[[-4 -3  2  9 15 19 21 20 14  8  2 -2]
 [31 28 31 30 31 30 31 31 30 31 30 31]]
shape: (2, 12)

correction:
[1 0]
shape: (2,)


ValueError: operands could not be broadcast together with shapes (2,12) (2,) 

In [7]:
correction_2d = correction.reshape(2, 1)

print("correction_2d:")
print(correction_2d)
print("shape:", correction_2d.shape)

result = rows + correction_2d

print("\nРезультат:")
print(result)


correction_2d:
[[1]
 [0]]
shape: (2, 1)

Результат:
[[-3 -2  3 10 16 20 22 21 15  9  3 -1]
 [31 28 31 30 31 30 31 31 30 31 30 31]]
